targets:
  $default:
    builders:
      injectable_generator:injectable_config_builder:
        generate_for:
          - lib/**.dart
      injectable_generator:injectable_builder:
        generate_for:
          - lib/**.dart