name: bdaya_flutter_common
description: Base Library for Bdaya Development Projects
version: 0.0.2
repository: https://github.com/Bdaya-Dev/bdaya_flutter_common

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"
flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
  class_name: BdayaLocalizations

dependencies:
  flutter:
    sdk: flutter
  bdaya_shared_value: ^3.1.3
  get_it: ^7.2.0
  flutter_hooks: ^0.18.5+1
  go_router: ^5.1.3
  logging: ^1.1.0
  tuple: ^2.0.1
  rxdart: ^0.27.5
  reactive_forms: ^14.1.0
  collection: ^1.16.0
  injectable: ^1.5.4
  intl: ^0.17.0
  url_strategy: ^0.2.0
  ansicolor: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.4
  build_runner: ^2.3.2
  intl_utils: ^2.7.0
