name: bdaya_flutter_common
description: Base Library for Bdaya Development Projects
version: 7.0.2
repository: https://github.com/Bdaya-Dev/bdaya_flutter_common

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  uses-material-design: true
dependencies:
  flutter:
    sdk: flutter
  bdaya_shared_value: ^3.1.3
  get_it: ^7.2.0
  flutter_hooks: ^0.19.0
  go_router: ^10.0.0
  logging: ^1.1.0
  rxdart: ^0.27.5
  reactive_forms: ^16.0.2
  collection: ^1.16.0
  injectable: ^2.1.0
  url_strategy: ^0.2.0
  ansicolor: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.3
  build_runner: ^2.3.2
  intl_utils: ^2.7.0
